### PR TITLE
Optional state

### PR DESCRIPTION
**Pull request by sm2017**

### CODE REVIEW

**Comment by retyui** [comment]
@sm2017 Nise work, Thanks!
Can you tell me what the problem do you want to fix? (`flow version - ?`)

**Comment by sm2017** [comment]
@retyui  i.e. `autoFocus` is optional props , But in flow you mark it as required

**Comment by sm2017** [comment]
image

**Comment by sm2017** [comment]
image

**Comment by retyui** [comment]
What version flow.js do you use?

**Comment by sm2017** [comment]
0.92.1

**Comment by retyui** [comment]
@sm2017 
I'm not sure that the errors in the screenshot below are related to flow.js (maybe phpStorm warnings)

Because the latest version of react-native using flow.js@0.86.0

And when you run `npx flow` you will understand it)

**Comment by sm2017** [comment]
Ok , thank you

**Pull request closed without merging**
