### PR TITLE
RTL Support

### PR DESCRIPTION
**Pull request by bamlhs**

### CODE REVIEW

**Comment by retyui** [comment]
@bamlhs How can I  test it?

**Comment by retyui** [comment]
The Travis CI build failed:

```sh
/home/travis/build/retyui/react-native-confirmation-code-field/src/components/ConfirmationCodeInput/styles.js
  34:22  error  Replace `(I18nManager.isRTL)` with `I18nManager.isRTL`  prettier/prettier
```
Please fix this error

**Comment by retyui** [comment]
Thank you!

**Comment by bamlhs** [comment]
> @bamlhs How can I test it?

in ios:   AppDelegate.m add 

    #import <React/RCTI18nUtil.h>
and in didFinishLaunchingWithOptions add these:
```
  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  [[RCTI18nUtil sharedInstance] forceRTL:YES];
```

for more please [read this](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps)

**Pull request merged**
