### PR TITLE
Fix text input update value

### PR DESCRIPTION
**Pull request by luancurti**
Passing a value to `CodeField` when value updates the `CodeField` will be update

### CODE REVIEW

**Comment by luancurti** [comment]
In my case the `CodeField` is rendered in the screen and I need to request permission to read `sms text` when user accept I need to change the `CodeField` value

**Comment by luancurti** [comment]
I tryed to use `defaultCode` prop but in this case this doesn't work

**Comment by retyui** [comment]
You can forse re-create instance:
```js
<CodeField defaultCode={value} key={value} />
```

Or call method `handlerOnTextChange`
```js
import React, { Component } from 'react';
import CodeInput from 'react-native-confirmation-code-field';

class App extends Component {
  handlerOnFulfill = code => console.log(code);

  field = createRef();

  pasteCode(){
      if(this.field.current){
        const value = '123';
        field.current.handlerOnTextChange(value);
      }
  }

  render() {
    return <CodeInput ref={this.field} onFulfill={this.handlerOnFulfill} />;
  }
}

```

**Comment by luancurti** [comment]
Thanks @retyui

**Pull request closed without merging**
